a. Cargar un valor negativo (ej. a3 = -3).

b. Si el numero es negativo se debe encender un led indicador.

c. Completa los espacios del siguiente código base:
li a3, -3
slti a4, a3, 0

d. ¿Qué valor tendrá a4 si a3 = 10?
si a3 vale 10 a4 vale 0
e. ¿Para qué sirve esta instrucción en programas reales?
En este ejercicio concreto: para saber si el número es negativo y, 
a partir de eso, decidir encender o no un LED indicador.